import json
from pathlib import Path


def save_output(result, filename, output_dir):
    base = filename.replace(".pdf", "")
    output_dir = Path(output_dir)

    # 1️⃣ Save JSON (structured)
    json_path = output_dir / f"{base}.json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2)

    # 2️⃣ Save Markdown (human-readable)
    md_path = output_dir / f"{base}.md"
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(render_markdown(result))


def render_markdown(r):
    lines = []

    lines.append("# Bias-Reduced Resume Summary\n")

    # Education
    lines.append("## Education")
    if r["Education"]:
        for e in r["Education"]:
            degree = e.get("degree", "Degree")
            field = e.get("field_of_study")
            inst = e.get("institution", "Institution")

            line = f"- **{degree.capitalize()}**"
            if field:
                line += f" — {field}"
            line += f"\n  *{inst}*"
            lines.append(line)
    else:
        lines.append("- Not provided")

    # Work Experience
    lines.append("\n## Work Experience")
    if r["WorkExperience"]:
        for w in r["WorkExperience"]:
            title = w.get("title", "Role")
            org = w.get("organization", "Organization")

            lines.append(f"### {title} — {org}")
            for resp in w.get("responsibilities", []):
                lines.append(f"- {resp}")
    else:
        lines.append("- Not provided")

    # Skills
    lines.append("\n## Skills")
    if r["Skills"]:
        lines.append(" · ".join(r["Skills"]))
    else:
        lines.append("Not provided")

    # Certifications
    lines.append("\n## Certifications")
    if r["Certifications"]:
        for c in r["Certifications"]:
            lines.append(f"- {c}")
    else:
        lines.append("Not provided")

    # Footer
    lines.append("\n---")
    lines.append("Generated by **HushHire**")

    return "\n".join(lines)
